export {
  REGISTERING_USER,
  REGISTERING_USER_SUCCESS,
  REGISTERING_USER_FAILURE,
  LOGIN_USER,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAILURE
} from './userAction';

export {
  FETCHING_ALL_SCHOOLS,
  FETCHING_ALL_SCHOOLS_SUCCESS,
  FETCHING_ALL_SCHOOLS_FAILURE
} from './schoolsAction';